channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==3.9.0
  - argparse==1.4.0
  - lz4==4.4.3
  - numpy==1.26.3
  - pandas==2.2.3
  - psutil==5.9.8
  - pyarrow==11.0.0
  - scikit-learn==1.7.2
  - scipy==1.10.1
  - xgboost==3.2.0
name: mlflow-env
